"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# Only loads the .env file if it exists
# In Production, the environment variables will be set in the environment, not in a file.
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("SECRET_KEY")  # secret key for cryptographic signing
DEBUG = os.getenv("DEBUG", "False") == "True"  # never set to True in production
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")  # domains allowed to serve the app
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")  # origins trusted for CSRF POST requests

# Security
X_FRAME_OPTIONS = "DENY"  # prevents site from being embedded in iframes
SECURE_CONTENT_TYPE_NOSNIFF = True  # prevents browser from guessing file content type
SECURE_REFERRER_POLICY = "same-origin"  # hides referrer URL on cross-origin requests
SESSION_COOKIE_HTTPONLY = True  # blocks JavaScript from reading the session cookie
SESSION_COOKIE_AGE = 3600  # session expires after 1 hour of inactivity

if not DEBUG:
    SECURE_SSL_REDIRECT = True  # redirects all HTTP requests to HTTPS
    SESSION_COOKIE_SECURE = True  # session cookie is only sent over HTTPS
    CSRF_COOKIE_SECURE = True  # CSRF cookie is only sent over HTTPS
    SECURE_HSTS_SECONDS = 31536000  # forces HTTPS for 1 year via browser header
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # applies HSTS to all subdomains
    SECURE_HSTS_PRELOAD = True  # allows site to be included in browser HSTS preload list


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "library_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),
# # for using specific schema other than public, uncomment below
# #         'OPTIONS': {
# #             'options': '-c search_path=public,public2'
# # }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # output folder for collectstatic

# login
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"
