# Generated by Django 6.0.4 on 2026-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0003_country_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published_at",
            field=models.DateField(null=True),
        ),
    ]
